name: Publish to NPM

on:
  push:
    branches: [main]
    paths:
      - 'packages/*/package.json'
      - 'packages/*/index.ts'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Get previous commit too
      - uses: oven-sh/setup-bun@v1
      
      - name: Setup NPM
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          
      - name: Publish packages
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Changed files:"
          git diff --name-only HEAD~1 2>/dev/null || git ls-files packages/
          
          # Manual trigger = publish all
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Manual mode - publishing all packages"
            for dir in packages/*/; do
              if [ -f "$dir/package.json" ]; then
                echo "Publishing $dir"
                cd $dir
                npm publish --access public || echo "Already published or error"
                cd ../..
              fi
            done
          else
            echo "Auto mode - publishing changed packages"
            # Auto trigger = only changed
            git diff --name-only HEAD~1 2>/dev/null | grep "packages/" | cut -d/ -f2 | sort -u | while read package; do
              echo "Publishing package: $package"
              if [ -d "packages/$package" ]; then
                cd packages/$package
                # Get current version from NPM
                NPM_VERSION=$(npm view $(node -p "require('./package.json').name") version 2>/dev/null || echo "0.0.0")
                LOCAL_VERSION=$(node -p "require('./package.json').version")
                if [ "$NPM_VERSION" = "$LOCAL_VERSION" ]; then
                  npm version patch --no-git-tag-version
                fi
                npm publish --access public || echo "Already published or error"
                cd ../..
              fi
            done
          fi