name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      
      - name: Build binaries
        run: |
          cd packages/fetch
          bun build index.ts --compile --target=bun-darwin-arm64 --outfile=yfetch-macos-arm64
          bun build index.ts --compile --target=bun-darwin-x64 --outfile=yfetch-macos-x64
          bun build index.ts --compile --target=bun-linux-x64 --outfile=yfetch-linux-x64
          bun build index.ts --compile --target=bun-linux-arm64 --outfile=yfetch-linux-arm64
          bun build index.ts --compile --target=bun-windows-x64 --outfile=yfetch.exe
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            packages/fetch/yfetch-*
            packages/fetch/*.exe
          generate_release_notes: true